#!/usr/bin/env bash
# transfer file to a server

if [ $# -lt 3 -o $# -gt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# == 3 ]
then
    scp -o StrictHostKeyChecking=no $1 "$3@$2:~/"
else
    scp -o StrictHostKeyChecking=no -i $4 $1 "$3@$2:~/"
fi
