#!/usr/bin/env bash
# install nginx, write string to html

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
expand="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
expand2="\n\terror_page 404 \/404.html;"
expand3="\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$expand/" /etc/nginx/sites-available/default
sudo sed -i "s/$expand2/$expand3/" /etc/nginx/sites-available/default
sudo service nginx restart
