#!/usr/bin/env bash
# makes it so listening port 80 is not refused 
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
