#!/usr/bin/env bash
# prints to infinity and beyond forever, prints i am invincible when sigterm
trap "echo 'i am invincible!!!'" SIGTERM

for (( ; ; ))
do
   echo "To infinity and beyond"
   sleep 2
done
