#!/usr/bin/env bash
# Print 10 lines of text
# 4th line badluck, 8th line good luck
# rest print holberton
i=1
while [ $i -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
    echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
    echo "good luck"
    else
    echo "Holberton School"
    fi

    ((i++))
done