#!/usr/bin/env bash
# Write a Bash script that displays:
# script that gives you information about the holbertonschool file.

name="holbertonschool"
if [ -e "$name" ]
then
    echo "$name file exists"
    if [ -s "$name" ]
    then
    echo "$name file is not empty"
    else
    echo "$name file is empty"
    fi
    if [ -f "$name" ]
    then
    echo "$name is a regular file"
    fi
else
    echo "$name file does not exist"
fi